spring.application.name=authservice

# Server Port
server.port=8080

# MongoDB Configuration
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.data.mongodb.database=NSPS_Auth_DB

# Security Config
jwt.secret=mysecretkey2026
jwt.expiration=86400000